# Generated by Django 4.1.5 on 2023-02-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
