# Generated by Django 4.1.5 on 2023-02-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_dm_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='veil',
            field=models.CharField(default='😉', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Unleash your thoughts, connect anonymously, and go beyond appearances on dm_me 🕶️'),
        ),
    ]
