# Generated by Django 4.1.7 on 2023-03-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('replyAt', models.DateTimeField(auto_now_add=True)),
                ('replyTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.dm')),
            ],
        ),
    ]
