# Generated by Django 4.1.5 on 2023-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
