# Generated by Django 4.1.5 on 2023-03-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
