# Generated by Django 4.1.5 on 2023-03-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_profile_blocked_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
