# Generated by Django 4.1.5 on 2023-03-27 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_ip_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='sentBy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.ip'),
        ),
    ]
