# Generated by Django 4.1.7 on 2023-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_dm_sentby_alter_ip_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
