# Generated by Django 4.1.7 on 2023-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_dm_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
