# Generated by Django 4.1.7 on 2023-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_dm_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.IntegerField(default=1),
        ),
    ]
