# Generated by Django 4.1.7 on 2023-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_profile_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Share crazy questions and confessions anonymously with me.'),
        ),
    ]
