# Generated by Django 4.0.6 on 2023-12-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Send anonymous messages to me !'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='veil',
            field=models.CharField(default='😉', max_length=2),
        ),
    ]
