# Generated by Django 4.0.6 on 2023-12-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_remove_profile_veil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
