# Generated by Django 4.0.6 on 2023-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_alter_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
