# Generated by Django 4.0.6 on 2023-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_alter_dm_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='isNotif',
            field=models.BooleanField(default=False),
        ),
    ]
