# Generated by Django 4.0.6 on 2024-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_dm_isnotif'),
    ]

    operations = [
        migrations.CreateModel(
            name='emojis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
    ]
