# Generated by Django 4.0.6 on 2024-01-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secque',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
