# Generated by Django 4.0.6 on 2024-04-09 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0032_profile_secque'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='isQuery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ip',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
