# Generated by Django 4.0.6 on 2024-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_dm_isquery_alter_ip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='dmType',
            field=models.IntegerField(default=1),
        ),
    ]
