# Generated by Django 5.1.4 on 2024-12-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_dm_dmtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
